### ISSUE TITLE
Switchbot Password & Switchbot Homeassistant State

### ISSUE THREAD

**Issue by Migz93** [fphammerle/switchbot-mqtt#37]
Thanks for this tool, it's working a treat for a switchbot that is just a little too far away from home assistant and used to only sporadically work.

I'm not sure if I missed something but is it possible to keep the password on my switchbot device to use with this? I couldn't find anywhere to specify the password so I had to remove it completely. Worried that anybody around me could get the switchbot app and activate that switchbot, I know it's fairly unlikely.

I was also wondering if as I have my switchbot set in press mode, if it's possible that when I turn it "on" in home assistant, it shortly afterwards sets itself back to off? I could set an automation to automatically set it back to "off" after being set to "on" but then that would activate the switchbot again which I don't want.

**Comment by fphammerle** [comment]
Hi,

> is it possible to keep the password on my switchbot device to use with this?

support for passwords has not yet been implemented, but it's on my todo list.
I am thinking about adding support for a config file with a mac address to password mapping, e.g.:
```yaml
# switchbot-passwords.yml
aa:bb:cc:dd:ee:ff: secret
dd:ee:ff:aa:bb:cc: password
```

> I was also wondering if as I have my switchbot set in press mode, if it's possible that when I turn it "on" in home assistant, it shortly afterwards sets itself back to off?

Could you use a `script` instead of `button`?

```yaml
# home assistant config
script:
  trigger_some_switchbot:
    sequence:
    - service: mqtt.publish
      data:
        topic: homeassistant/switch/switchbot/aa:bb:cc:dd:ee:ff/state
        payload: ON
 ```
