### ISSUE TITLE
Battery "fetch-device-info" with docker-compose

### ISSUE THREAD

**Issue by matt8707** [fphammerle/switchbot-mqtt#50]
Continuing https://github.com/fphammerle/switchbot-mqtt/issues/41#issuecomment-944912178

I'm unsure how to pass the `--fetch-device-info` command-line option in `docker-compose`

I've tried variations of `command: --fetch-device-info` and passing it along a mqtt payload

**Comment by matt8707** [comment]
That was fast! Yes, that works 👍🏻 

![screen](https://user-images.githubusercontent.com/36163594/137972087-a066dc45-36cc-48c1-a20b-46ed193172bc.jpg)

```yaml
  switchbot-mqtt:
    image: fphammerle/switchbot-mqtt:2.1.0-armv7
    container_name: switchbot-mqtt
    restart: always
    network_mode: host
    userns_mode: host
    cap_add:
      - NET_ADMIN
    cap_drop:
      - ALL
    user: '0'
    environment:
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - FETCH_DEVICE_INFO=yes

```
